# OpenAPI (minimal)
quarkus.smallrye-openapi.info-title=Warranty Tracker API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.swagger-ui.enable=true
quarkus.smallrye-openapi.enable=true


quarkus.datasource.jdbc.url=${SUPABASE_DB_URL}
quarkus.datasource.username=${SUPABASE_DB_USER}
quarkus.datasource.password=${SUPABASE_DB_PASSWORD}
# AWS Configuration
quarkus.s3.aws.region=us-east-1
quarkus.s3.aws.credentials.type=default
app.s3.bucket-name=warranty-tracker-dev
