# Base path for API
quarkus.http.root-path=/api

# Optimized logging for Lambda
#quarkus.log.level=INFO
#quarkus.log.category."com.nazri".level=INFO
#quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] %s%e%n

# AWS Lambda optimizations
quarkus.arc.remove-unused-beans=true
quarkus.arc.detect-unused-false-positives=false

# Native compilation optimizations
quarkus.native.additional-build-args=--initialize-at-build-time=org.slf4j,--no-fallback
quarkus.native.enable-https-url-handler=false

quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.schema-management.strategy=update
#quarkus.hibernate-orm.schema-management.strategy=validate

# Pagination configuration
app.pagination.default-size=20
app.pagination.max-size=20
app.pagination.max-page=500
