quarkus.swagger-ui.enable=false
quarkus.smallrye-openapi.enable=false

## Lambda-specific
quarkus.lambda.enable-polling-jvm-mode=false

quarkus.datasource.jdbc.url=${SUPABASE_PROD_DB_URL}
quarkus.datasource.username=${SUPABASE_PROD_DB_USER}
quarkus.datasource.password=${SUPABASE_PROD_DB_PASSWORD}