quarkus.swagger-ui.enable=false
quarkus.smallrye-openapi.enable=false

quarkus.datasource.jdbc.url=${SUPABASE_PROD_DB_URL}
quarkus.datasource.username=${SUPABASE_PROD_DB_USER}
quarkus.datasource.password=${SUPABASE_PROD_DB_PASSWORD}
# AWS Configuration
quarkus.s3.aws.region=us-east-1
quarkus.s3.aws.credentials.type=default
app.s3.bucket-name=warranty-tracker-prod
